format = """
[](#9A348E)\
$username\
[](bg:blue fg:#9A348E)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_state\
$git_status\
[](fg:green)\
"""

right_format = """
$character
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bold bg:#9A348E fg:white"
style_root = "bold bg:#9A348E fg:white"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Dropbox" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[ $symbol $branch ]($style)'

[git_state]
style = "bg:green"

[git_status]
style = "bg:green"
format = '[$all_status$ahead_behind ]($style)'

[character]
format = '$symbol '
success_symbol = '[✔](bold green)'
error_symbol = '[✘](bold red)'
